- hosts: masters
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt


- hosts: masters
  become: yes
  tasks:
    - name: get worker nodes
      become_user: niel
      shell: kubectl get nodes --selector=node-role.kubernetes.io/master!= --no-headers | awk '{print $1}'
      register: worker_nodes

    - name: label worker nodes
      become_user: niel
      shell: kubectl label node "{{ item }}" node-role.kubernetes.io/worker=worker
      with_items: "{{ worker_nodes.stdout_lines }}"
